### ISSUE TITLE
[Feature Request] Support for consistent form behaviour on different screen resolutions

### ISSUE THREAD

**Issue by steve-d-mottram** [archi-contribs/form-plugin#13]
Hi - the forms plugin almost satisfies an important need for my team, but there is one issue: Because the form controls are laid out using x:y pixel spacing, a form designed on my PC using a 4k monitor needs different pixel positions from my colleagues working on the same model (through the collaboration plugin) who have different monitor setups. In other words, the form definition is not portable across different screen resolutions.

It would be a major improvement if the forms and the form editor used an auto-sizing grid-based layout, or if that is too hard to implement, at least a percentage-based positioning. I appreciate that the plugin is in its early stages, and you may already have this in your plans.

**Comment by herve91** [comment]
Hi Steve

Thanks for your kind words.

I currently have a standard monitor at work and 4K monitors home and do not experience huge differences between both of them because Eclipse is doing automatic scaling.

Could you please send me a screenshot of your form in both screens that I can compare. You may send them on my email faktor_1@yahoo.fr if you do not wish to publish them on GitHub (which I can understand).

Best regards
Hervé

**Comment by steve-d-mottram** [comment]
Hi, I'm sorry for the delay in responding. I'm now not able to reproduce the issue, so it's probably best to close this issue, and I'll get back to you if I see it again. Thanks for a great piece of work on this plugin.
