### ISSUE TITLE
Updates are not done through commands...

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/form-plugin#2]
Hi,

I've just played a bit with this plugin and I really like it. In addition to the obvious (already known) todos (like filters), it is important to change the way properties are updated. It seems that you are directly changing values to the EMF objects, but you should not do it this way in Archi (in fact in any GEF based application). You have to create "commands". This is needed to integrate with the undo/redo stack. 

Let me know if at some point you want me to look at it (I have a similar need for another plugin).

JB

**Comment by Phillipus** [comment]
JB is correct. If you are changing the EMF model in any way then you have to use an Undo/Redo Command. Every model change should be undoable.

**Comment by herve91** [comment]
You are right ;-P
I'll learn commands then ... hopefully, google is my friend :-)

What do you suggest, one undo/redo per property update in the form, or one global undo/redo for the whole form ?

**Comment by Phillipus** [comment]
Google won't help. Take a look at class:

com.archimatetool.editor.propertysections.UserPropertiesSection for an example.

**Comment by herve91** [comment]
I just had a look to your UserPropertySection and to be honest, I do not understand it ... I do not even knok where to start looking at (1162 lines begins to be quite a huge file for an example) ...

You overestimate my skills, mate ...

Few months ago, I didn't even know the Java language and it is the first time I'm using the Eclipse framework ... I do not know what a command is, nor how it works.

That's why I need to read few documentation and some simple examples that I can understand :-) And when it is related to search for documentation and tutorials, google is my friends. QED :-)

Anyway, please continue to point out what I do wrong than I can improve :-)

**Comment by herve91** [comment]
After few months of study, I finally understood how Eclipse commands work.

Rather than updating the Archi properties on every keystoke, I added an "OK" button which saves the variables values in one single shot.

I added this update in an Eclipse command, enabling to undo / redo the whole form updates.

This has been implemented in the version 1.1.

**Comment by jbsarrodie** [comment]
Great. I really have to find some time to test the latest version !

**Comment by Phillipus** [comment]
> I finally understood how Eclipse commands work.

Nice. Well done!
